# Site settings
title: Mac OS X Versions
email: chilcotr@ohio.edu
baseurl: "/macosxversions" # the subpath of your site, e.g. /blog/
url: "http://munkiserver.github.io" # the base hostname & protocol for your site